import org.apache.commons.cli.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;


/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'baxue' at '11/25/14 10:29 PM' with Gradle 2.1
 *
 * @author baxue, @date 11/25/14 10:29 PM
 */
public class CCHelper {

    static Logger logger = LoggerFactory.getLogger(CCHelper.class.getClass());

    public static void main(String[] args) throws ParseException {

        // create the parser
        CommandLineParser parser = new GnuParser();
        Options options = new Options();

        options.addOption("l", true, "local change folder/file");
        options.addOption("c", true, "clear case folder/file");

        CommandLine line = parser.parse(options, args);
        String changePath = ".";
        if (line.hasOption("l")) {
            changePath = line.getOptionValue("l");
            logger.debug(changePath);
        }

        String clearCasePath = ".";
        if (line.hasOption("c")) {
            clearCasePath = line.getOptionValue("c");
            logger.debug(clearCasePath);
        }

        Compare compare = new Compare();
        try {
            compare.getDiff(new File(changePath), new File(clearCasePath));
        } catch (IOException ie) {
            ie.printStackTrace();
        }

    }
}
