import org.apache.commons.cli.*;

import java.io.File;
import java.io.IOException;


/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'baxue' at '11/25/14 10:29 PM' with Gradle 2.1
 *
 * @author baxue, @date 11/25/14 10:29 PM
 */
public class CCheckin {


    public static void main(String[] args) throws ParseException {

        // create the parser
        CommandLineParser parser = new GnuParser();
        Options options = new Options();

        options.addOption("l", true, "local change folder/file");
        options.addOption("c", true, "clear case folder/file");

        CommandLine line = parser.parse(options, args);
        String changePath = ".";
        if (line.hasOption("l")) {
            changePath = line.getOptionValue("l");
            System.out.println(changePath);
        }

        String clearCasePath = ".";
        if (line.hasOption("c")) {
            clearCasePath = line.getOptionValue("c");
            System.out.println(clearCasePath);
        }

        Compare compare = new Compare();
        try {
            File dirA = new File(changePath);
            File dirB = new File(clearCasePath);
            if (!dirA.exists()) {
                System.err.println("need input local dir");
                System.exit(0);
            }
            if (!dirB.exists()) {
                System.err.println("need input clear case dir");
                System.exit(0);
            }
            compare.getDiff(dirA, dirB);
        } catch (IOException ie) {
            ie.printStackTrace();
        }
    }
}
